
# Setup
title:               dllib
email:               lewuathe@me.com
tagline:             "A distributed deep learning framework running on Apache Spark"
url:                 "" # insert your site's URL
baseurl:             "/dllib/"

# About/contact
author: # you can edit these to be your personal details
  name:              Kai Sasaki
  url:               https://www.lewuathe.com
  email:

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: "UA-44055098-3"
google_tag_manager:
# Bing services
bing_verification:

# Social
github_username: Lewuathe
twitter_username: Lewuathe
facebook: lewuathe
linkedin_username: kaisasaki

# Custom vars
version:             0.0.8
github:              https://github.com/Lewuathe/dllib
repo:                https://github.com/Lewuathe/dllib

# Gems - Dependencies for this theme
gems:
  # None currently

# Build settings
markdown:     kramdown
permalink:    pretty
